TemperatureMonitoring/Controllers/InputTemperatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TemperatureMonitoring.CustomAuthorize;
using TemperatureMonitoring.Models;
using TemperatureMonitoring.Repository;
using TemperatureMonitoring.Repository.Device;
using TemperatureMonitoring.Repository.InputTemperature;

namespace TemperatureMonitoring.Controllers
{
    [CustomAuthorize(Roles = "Administrator,Manager,Staff")]
    public class InputTemperatureController : Controller
    {
        DeviceRepository _deviceRepository = new DeviceRepository();
        // GET: InputTemperature
        public ActionResult Index()
        {
            List<CDevice> lsdevices = _deviceRepository.GetListDevice(User.Identity.Name);
            List<CInputTemperature> _lscInputTemperatures = new List<CInputTemperature>();
            foreach (var item in lsdevices)
            {
                CInputTemperature _cInputTemperature = new CInputTemperature();
                _cInputTemperature.Warehouse = item.Warehouse;
                _cInputTemperature.DeviceID = item.DeviceID;
                _cInputTemperature.DeviceName = item.DeviceName;
                _cInputTemperature.LeftDevice = "";
                _cInputTemperature.RightDevice = "";
                _cInputTemperature.Remark = "";
                _cInputTemperature.UserInput = User.Identity.Name;
                _lscInputTemperatures.Add(_cInputTemperature);
                
            }
            ViewBag.UserAction = User.Identity.Name;
            return View(_lscInputTemperatures);
        }

        // GET: InputTemperature/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InputTemperature/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InputTemperature/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: InputTemperature/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InputTemperature/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: InputTemperature/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        public JsonResult SaveData(List<CInputTemperature> values)  //JsonResult
        {
            var json = new JavaScriptSerializer().Serialize(values);
            InputtemperatureRepository inputtemperatureRepository = new InputtemperatureRepository();
            string _TimeInput = "";
            _TimeInput = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            if (values == null)
            {
                values = new List<CInputTemperature>();
            }
            string _result = "";
            foreach (var item in values)
            {
                _result += inputtemperatureRepository.InputTemperatureInsert(item.Warehouse, item.DeviceID, item.LeftDevice, item.RightDevice, _TimeInput,User.Identity.Name, item.Remark);
            }
            ResultData _resultData = new ResultData();
            if (_result.Trim() == "")
            {
                //string[] emailto = new string[]{};
                UserLoginRepository _userlogin = new UserLoginRepository();
                List<UserSendEmail> _usersendmails= _userlogin.GetUserSendEmail(User.Identity.Name);
                string[] emailto = new string[_usersendmails.Count];
                int iuser = 0;
                foreach (var _userSendmail in _usersendmails)
                {
                    emailto[iuser] = _userSendmail.Email;
                    iuser=iuser+1;
                }
                //new string [] { "minhsang.nguyen@vn.yusen-logistics.com" }
                SendMail.SendmailTemp(emailto, "test send mail", GetStringBodySendmail(values), "");
                _resultData.Status = "Success";
                _resultData.TimeInput = _TimeInput;
                _resultData.Error = "Gửi thông tin thành công. Xin cảm ơn";
            }
            else
            {
                _resultData.Status = "Error";
                _resultData.TimeInput = "";
                _resultData.Error = "Lỗi: " + _result;
            }

            return Json(_resultData);
            //return RedirectToAction("SaveData");
        }


        // POST: InputTemperature/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Report(string FromDate="", string ToDate="")
        {
            InputtemperatureRepository inputtemperatureRepository = new InputtemperatureRepository();
           
            if (FromDate =="")
            {
                ViewBag.FromDate = DateTime.Now.Date.ToString("yyyy-MM-dd");
            }
            else
            {
                ViewBag.FromDate = FromDate;
            }
            if (ToDate == "")
            {
                ViewBag.ToDate = DateTime.Now.Date.ToString("yyyy-MM-dd");
            }
            else
            {
                ViewBag.ToDate = ToDate;
            }
            List<CInputTemperature> ls_cInputTemperature = inputtemperatureRepository.InputTemperatureGET(ViewBag.FromDate,ViewBag.ToDate, User.Identity.Name);
            List<CInputTemperature> _lscInputTemperatures = new List<CInputTemperature>();
            foreach (var item in ls_cInputTemperature)
            {
                CInputTemperature _cInputTemperature = new CInputTemperature();
                _cInputTemperature.Warehouse = item.Warehouse;
                _cInputTemperature.DeviceID = item.DeviceID;
                _cInputTemperature.DeviceName = item.DeviceName;
                _cInputTemperature.LeftDevice = item.LeftDevice;
                _cInputTemperature.RightDevice = item.RightDevice;
                _cInputTemperature.Remark = item.Remark;
                _cInputTemperature.UserInput = item.UserInput;
                _cInputTemperature.TimeInput = item.TimeInput;
                _lscInputTemperatures.Add(_cInputTemperature);
            }
            return View(_lscInputTemperatures);
        }
        private string GetStringBodySendmail(List<CInputTemperature> values)
        {
            string _result = "";
            string _body = "";
            foreach (var item in values)
            {
                _body = _body + $@"<tr bgcolor='#FFFFFF'><td><b>BTLC</b></td> <td> <b> {item.DeviceName}	 </b> </td> <td> <b> {item.LeftDevice}</b></td> <td> <b>{item.RightDevice}</b></td> <td> <b> </b></td> <td> <b> {item.TimeInput}</b></td> <td> <b>{item.UserInput}</b></td> </tr> ";
            }
            _result = @"<p>Dear team,</p>
                        <p>Đây là mail gửi báo cáo ghi nhận nhiệt độ lúc: 2021-05-20 17:14:02</p>
                    <table border=" + 0 + " cellpadding=" + 0 + " cellspacing=" + 0 + " width = " + 800 + ">" +
                "<tr bgcolor='#4da6ff'><td><b>Warehouse</b></td> <td> <b> Device </b> </td> <td> <b> Nhiệt độ IN</b></td> <td> <b> Nhiệt độ OUT</b></td> <td> <b> Ghi Chú</b></td> <td> <b> Thời gian ghi nhận</b></td> <td> <b> Người ghi nhận</b></td> </tr> " +
                 _body +
                "</table> </br></br>" +
                "*************************************************************************************</br> "+
                "This is an auto - generated email.Please do not reply to this email or its recipients.</br>" +
                "************************************************************************************* "
                ;
            return _result;
        }
        
        
    }
    public class ResultData
    {
        public string Status { get; set; }
        public string Error { get; set; }
        public string TimeInput { get; set; }
    }
}

TemperatureMonitoring/Views/InputTemperature/ConfirmInput.cshtml
@model IEnumerable<TemperatureMonitoring.Models.CInputTemperature>

@{
    ViewBag.Title = "ConfirmInput";
}

<h2>Xác nhận thông tin nhiệt độ</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Warehouse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeviceID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeviceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeftDevice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RightDevice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Remark)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeInput)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserInput)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Warehouse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeviceID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeviceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LeftDevice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RightDevice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Remark)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeInput)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserInput)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>

TemperatureMonitoring/Views/InputTemperature/Create.cshtml
@model TemperatureMonitoring.Models.CInputTemperature

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ClnputTemperature</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Warehouse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Warehouse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Warehouse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeftDevice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeftDevice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeftDevice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightDevice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RightDevice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RightDevice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeInput, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeInput, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.TimeInput, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserInput, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserInput, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserInput, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@
@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "yy/mm/dd",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>

}

TemperatureMonitoring/Views/InputTemperature/Index.cshtml
@model IEnumerable<TemperatureMonitoring.Models.CInputTemperature>

@{
    ViewBag.Title = "Index";
}

<h2>GHI NHẬN THÔNG TIN NHIỆT ĐỘ</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
    @*<a href="#finish">Lưu thông tin</a>*@

    <div>
        <label>Người gửi:  @ViewBag.UserAction</label>
        <br />
        <label>Thời gian gửi: </label>
        <script>

            var today = new Date();

            var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();

            var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();

            var dateTime = date + ' ' + time;
            document.write(dateTime);
        </script>
        <br />
        <label id="lblThongBao">***Vui lòng báo cho quản lý kho nếu có điều bất thường nào!*** </label>
        @*@Html.Label("Người gửi: ")
            @Html.Label("Thời gian: ")
            @Html.Label("Vui lòng báo cho quản lý kho nếu có điều bất thường nào!")*@
    </div>
</p>
<table class="table">
    <tr>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.Warehouse)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.DeviceID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeviceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeftDevice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RightDevice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Remark)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.TimeInput)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.UserInput)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="display:none">
                @Html.DisplayFor(modelItem => item.Warehouse)
            </td>
            <td style="display:none">
                @Html.DisplayFor(modelItem => item.DeviceID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeviceName)
            </td>
            <td>
                @Html.EditorFor(modelItem => item.LeftDevice, new { htmlAttributes = new { @class = "form-control", @id = "left_" + item.Warehouse + item.DeviceID } })
            </td>
            <td>
                @Html.EditorFor(modelItem => item.RightDevice, new { htmlAttributes = new { @class = "form-control", @id = "right_" + item.Warehouse + item.DeviceID } })
            </td>
            <td>
                @Html.EditorFor(modelItem => item.Remark, new { htmlAttributes = new { @class = "form-control", @id = "remark_" + item.Warehouse + item.DeviceID } })
            </td>
            <td style="display:none">
                @Html.DisplayFor(modelItem => item.TimeInput)
            </td>
            <td style="display:none">
                @Html.DisplayFor(modelItem => item.UserInput)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    <a class="edit" href="#">Sửa</a>
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>

<input type="submit"
       value="GỬI THÔNG TIN"
       class="btn btn-default"
       id="finish" />
<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script>
    $('.edit').click(function () {
        var row = $(this).closest('tr');
        row.toggleClass('isediting'); // add a style to highlight the row
        var isediting = row.hasClass('isediting');
        $(this).parent('td').siblings('td').prop('contenteditable', isediting);
        if (isediting) {
            $(this).text('Lưu');
        } else {
            $(this).text('Sửa');
        }
    })

</script>
<script>
    function myTrim(x) {
        return x.replace(/^\s+|\s+$/gm, '');
    }
    $(document).ready(function () {
        $('#finish').click(function (e) {
            // prevent the default event behaviour
            e.preventDefault();
            var strlableInformation = "";
            if ($('#finish').val() == "GỬI THÔNG TIN") {
                var validateinfor = "";
                $('.table tr').each(function (row, tr) {
                    //TableData = TableData + $(tr).find('td:eq(0)').text() + "-" + $(tr).find('td:eq(1)').text() + ",";
                    var row = $(this);


                    if ($(tr).find('td:eq(0)').text().trim() != "") {
                        document.getElementById($(tr).find('input:eq(0)').attr('id')).readOnly = true;
                        document.getElementById($(tr).find('input:eq(1)').attr('id')).readOnly = true;
                        document.getElementById($(tr).find('input:eq(2)').attr('id')).readOnly = true;
                        if (isFinite($(tr).find('input:eq(0)').val().trim())) {//in
                            if ($(tr).find('input:eq(0)').val().trim() >0) {
                                document.getElementById($(tr).find('input:eq(0)').attr('id')).style.color = "red";

                                strlableInformation = strlableInformation + $(tr).find('td:eq(2)').text().trim() + " IN \n";
                            }
                            else {
                                document.getElementById($(tr).find('input:eq(0)').attr('id')).style.color = "black";
                            }

                        }
                        else {
                            document.getElementById($(tr).find('input:eq(0)').attr('id')).style.color = "red";
                            strlableInformation = strlableInformation + $(tr).find('td:eq(2)').text().trim() + " IN \n";
                        }
                        //out
                        if (isFinite($(tr).find('input:eq(1)').val().trim())) { //out
                            if ($(tr).find('input:eq(1)').val().trim() > 8) {
                                document.getElementById($(tr).find('input:eq(1)').attr('id')).style.color = "red";
                                strlableInformation = strlableInformation + $(tr).find('td:eq(2)').text().trim() + " OUT \n";
                            }
                            else {
                                document.getElementById($(tr).find('input:eq(1)').attr('id')).style.color = "black";
                            }

                        }
                        else {
                            document.getElementById($(tr).find('input:eq(1)').attr('id')).style.color = "red";
                            strlableInformation = strlableInformation + $(tr).find('td:eq(2)').text().trim() + " OUT \n";
                        }
                        var temIN = "";
                        temIN = $(tr).find('input:eq(0)').val();
                        console.log("rrr:" + temIN)
                        var temOUT = "";
                        temOUT = $(tr).find('input:eq(1)').val();
                        if (myTrim(temIN) == "" || myTrim(temOUT) == "") {
                            //alert("Bạn chưa nhập nhiệt độ IN OUT");
                            validateinfor += "Bạn chưa nhập nhiệt độ IN OUT của thiết bị: " + $(tr).find('td:eq(2)').text().trim() + "\n";
                            //document.getElementById($(tr).find('input:eq(0)').attr('id')).readOnly = false;
                            //document.getElementById($(tr).find('input:eq(1)').attr('id')).readOnly = false;
                            //document.getElementById($(tr).find('input:eq(2)').attr('id')).readOnly = false;
                        }
                    }

                });
                if (validateinfor.length > 0) {
                    $('.table tr').each(function (row, tr) {
                        if ($(tr).find('td:eq(0)').text().trim() != "") {
                            document.getElementById($(tr).find('input:eq(0)').attr('id')).readOnly = false;
                            document.getElementById($(tr).find('input:eq(1)').attr('id')).readOnly = false;
                            document.getElementById($(tr).find('input:eq(2)').attr('id')).readOnly = false;
                        }
                    });
                }

                if (strlableInformation.length > 0) {
                    document.getElementById('lblThongBao').innerHTML = '*** Vui lòng thông báo cho quản lý nhiệt độ ở thiết bị ' + strlableInformation + ' đang bất thường ***';
                    document.getElementById('lblThongBao').style.color = "red";
                }
                else {
                    document.getElementById('lblThongBao').innerHTML = '*** Tất cả đang bình thường! ***';
                    document.getElementById('lblThongBao').style.color = "#06183D";
                }

                if (validateinfor.length>0) {
                    alert(validateinfor)
                }
                else {
                    alert("Vui lòng xác nhận thông tin đã ghi nhận")
                    $('#finish').val("XÁC NHẬN THÔNG TIN");
                }

            }
            else {
                $('#finish').val("GỬI THÔNG TIN");

                var TableData = new Array();
                var errorInput = "";
                $('.table tr').each(function (row, tr) {
                    //TableData = TableData + $(tr).find('td:eq(0)').text() + "-" + $(tr).find('td:eq(1)').text() + ",";
                    var row = $(this);
                    var temperature = {};
                    if ($(tr).find('td:eq(0)').text().trim() != "") {
                        temperature.Warehouse = $(tr).find('td:eq(0)').text().trim();
                        temperature.DeviceID = $(tr).find('td:eq(1)').text().trim();
                        temperature.DeviceName = $(tr).find('td:eq(2)').text().trim();
                        temperature.LeftDevice = $(tr).find('input:eq(0)').val().trim();
                        temperature.RightDevice = $(tr).find('input:eq(1)').val().trim();
                        temperature.Remark = $(tr).find('input:eq(2)').val().trim();
                        if (temperature.LeftDevice == "" || temperature.RightDevice == "") {
                            //alert("Bạn chưa nhập nhiệt độ IN OUT");
                            errorInput += "Bạn chưa nhập nhiệt độ IN OUT của thiết bị: " + temperature.DeviceName + "\n";
                            document.getElementById($(tr).find('input:eq(0)').attr('id')).readOnly = false;
                            document.getElementById($(tr).find('input:eq(1)').attr('id')).readOnly = false;
                            document.getElementById($(tr).find('input:eq(2)').attr('id')).readOnly = false;
                        }
                        TableData.push(temperature);
                    }
                });
                if (errorInput.length > 0) {
                    alert(errorInput);
                    return;
                }
                $('.table tr').each(function (row, tr) {
                    //TableData = TableData + $(tr).find('td:eq(0)').text() + "-" + $(tr).find('td:eq(1)').text() + ",";
                    var row = $(this);

                    if ($(tr).find('td:eq(0)').text().trim() != "") {

                        document.getElementById($(tr).find('input:eq(0)').attr('id')).readOnly = false;
                        document.getElementById($(tr).find('input:eq(1)').attr('id')).readOnly = false;
                        document.getElementById($(tr).find('input:eq(2)').attr('id')).readOnly = false;

                    }
                });
                var postData = { values: TableData };

                $.ajax({
                    url: "/InputTemperature/SaveData",
                    type: "POST",
                    data: JSON.stringify(postData),// TableData,
                    dataType: "json",
                    //traditional: true,
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {

                        // perform your save call here

                        if (data.Status == "Success") {
                            alert(data.Error);
                            var fromdate = data.TimeInput;
                            var todate = data.TimeInput;
                            window.location = '@Url.Action("Report", "InputTemperature")?FromDate=' + fromdate + '&ToDate=' + todate;
                        } else {

                            alert(data.Error);
                        }
                    },
                    error: function () {
                        //alert("An error has occured!!!");
                    }
                });

            }

            return;

        });
    });
</script>     

TemperatureMonitoring/Views/InputTemperature/Report.cshtml
@model IEnumerable<TemperatureMonitoring.Models.CInputTemperature>

@{
    ViewBag.Title = "Report";
}

<h2>Báo cáo</h2>
<div>
    <label for="FromDate">Từ ngày</label>
    <input id="FromDate" name="FromDate" type="date" value="@Convert.ToDateTime(@ViewBag.FromDate).ToString("yyyy-MM-dd")" />
    <label for="ToDate">Đến ngày</label>
    <input id="ToDate" name="ToDate" type="date" value="@Convert.ToDateTime(@ViewBag.ToDate).ToString("yyyy-MM-dd")" />
    <input type="submit"
           value="View"
           class="btn btn-default"
           id="link" />
    @*<a target="_blank" href="@Url.Action("Report","InputTemperature", new { FromDate = "FromDate", ToDate = "ToDate"})"></a>*@
</div>
<p>
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TimeInput)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Warehouse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeviceID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeviceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeftDevice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RightDevice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Remark)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserInput)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.TimeInput)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Warehouse)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DeviceID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DeviceName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LeftDevice)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RightDevice)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Remark)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserInput)
    </td>
    @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
</tr>
    }

</table>
@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "yy/mm/dd",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>
    <script>
        $('#link').click(function () {
            var fromdate = $('#FromDate').val();
            var todate = $('#ToDate').val() +" 23:59:59";
            console.log(todate);
            window.location = '@Url.Action("Report", "InputTemperature")?FromDate=' + fromdate + '&ToDate=' + todate;
            })
    </script>
    

}